// auto-generated · per-book overrides for Ghazali-template SPA
window.BOOK_T = {
  "ar": {
    "appTitle": "من هو اليهودي ؟",
    "splashSub": "Man huwa al-yahūdī ?",
    "splashHint": "اضغط للتخطي",
    "sacredRef": "عبد الوهاب المسيري · ١٩٣٨ – ٢٠٠٨",
    "tabHome": "الرئيسية",
    "tabCards": "الأفكار",
    "tabQuiz": "المفاهيم",
    "tabProgress": "تقدّم",
    "tabAbout": "الكتاب",
    "cardsTitle": "أفكار من الكتاب",
    "cardsDesc": "مقتطفات مفتاحية",
    "quizTitle": "مفاهيم مفتاحية",
    "quizDesc": "اختبر فهمك",
    "progressTitle": "تقدّمي",
    "progressDesc": "مسارك في الكتاب",
    "helpTitle": "❓ مساعدة",
    "duaPanelTitle": "📜 اقتباسات",
    "dailyLabel": "✨ فكرة اليوم",
    "searchPlaceholder": "ابحث في الأفكار...",
    "share": "مشاركة",
    "verse": "اقتباس",
    "hadith": "السياق",
    "apply": "💭 للتأمل",
    "youngMode": "🌟 نسخة مبسطة",
    "teenMode": "📖 نسخة كاملة",
    "xpLabel": "نقاط القراءة",
    "levelLabel": "مستوى",
    "streakMsg": "أيام متواصلة!",
    "readMore": "اقرأ المزيد",
    "nextQ": "السؤال التالي",
    "lifeline5050": "50/50",
    "lifelineHint": "💡 تلميح",
    "lifelineQuran": "📖 مرجع",
    "correct": "إجابة صحيحة! 🎉",
    "wrong": "حاول مرة أخرى 💪",
    "quizComplete": "اكتمل الاختبار!",
    "score": "النتيجة",
    "tryAgain": "أعد المحاولة",
    "badge_beginner": "مبتدئ",
    "badge_reader": "قارئ",
    "badge_scholar": "باحث",
    "badge_persistent": "مثابر",
    "badge_expert": "خبير",
    "splashFeatures": [
      "كتاب من هو اليهودي ؟",
      "أفكار مفتاحية مع نصوص أصلية",
      "ترجمة فرنسية كاملة (PDF)",
      "تطبيق ثلاثي اللغة"
    ]
  },
  "en": {
    "appTitle": "Qui est juif ?",
    "splashSub": "Man huwa al-yahūdī ?",
    "splashHint": "tap to skip",
    "sacredRef": "ʿAbd al-Wahhāb al-Massīrī · 1938 – 2008",
    "tabHome": "Home",
    "tabCards": "Ideas",
    "tabQuiz": "Concepts",
    "tabProgress": "Progress",
    "tabAbout": "Book",
    "cardsTitle": "Key Ideas",
    "cardsDesc": "Selected excerpts",
    "quizTitle": "Key Concepts",
    "quizDesc": "Test your understanding",
    "progressTitle": "My Progress",
    "progressDesc": "Your reading journey",
    "helpTitle": "❓ Help",
    "duaPanelTitle": "📜 Quotes",
    "dailyLabel": "✨ Idea of the Day",
    "searchPlaceholder": "Search ideas...",
    "share": "Share",
    "verse": "Original",
    "hadith": "Context",
    "apply": "💭 To reflect upon",
    "youngMode": "🌟 Brief",
    "teenMode": "📖 Full",
    "xpLabel": "Reading Points",
    "levelLabel": "Level",
    "streakMsg": "consecutive days!",
    "readMore": "Read More",
    "nextQ": "Next Question",
    "lifeline5050": "50/50",
    "lifelineHint": "💡 Hint",
    "lifelineQuran": "📖 Reference",
    "correct": "Correct! 🎉",
    "wrong": "Try again 💪",
    "quizComplete": "Quiz Complete!",
    "score": "Score",
    "tryAgain": "Retry",
    "badge_beginner": "Beginner",
    "badge_reader": "Reader",
    "badge_scholar": "Scholar",
    "badge_persistent": "Persistent",
    "badge_expert": "Expert",
    "splashFeatures": [
      "Qui est juif ?",
      "Key ideas with original texts",
      "Full French translation (PDF)",
      "Trilingual interactive app"
    ]
  },
  "fr": {
    "appTitle": "Qui est juif ?",
    "splashSub": "Man huwa al-yahūdī ?",
    "splashHint": "appuyez pour passer",
    "sacredRef": "ʿAbd al-Wahhāb al-Massīrī · 1938 – 2008",
    "tabHome": "Accueil",
    "tabCards": "Idées",
    "tabQuiz": "Concepts",
    "tabProgress": "Progrès",
    "tabAbout": "Livre",
    "cardsTitle": "Idées-clés",
    "cardsDesc": "Extraits choisis",
    "quizTitle": "Concepts-clés",
    "quizDesc": "Testez votre compréhension",
    "progressTitle": "Ma progression",
    "progressDesc": "Votre parcours",
    "helpTitle": "❓ Aide",
    "duaPanelTitle": "📜 Citations",
    "dailyLabel": "✨ Idée du jour",
    "searchPlaceholder": "Rechercher...",
    "share": "Partager",
    "verse": "Original",
    "hadith": "Contexte",
    "apply": "💭 À méditer",
    "youngMode": "🌟 Court",
    "teenMode": "📖 Complet",
    "xpLabel": "Points de lecture",
    "levelLabel": "Niveau",
    "streakMsg": "jours consécutifs !",
    "readMore": "Lire plus",
    "nextQ": "Question suivante",
    "lifeline5050": "50/50",
    "lifelineHint": "💡 Indice",
    "lifelineQuran": "📖 Référence",
    "correct": "Correct ! 🎉",
    "wrong": "Réessayez 💪",
    "quizComplete": "Quiz terminé !",
    "score": "Score",
    "tryAgain": "Recommencer",
    "badge_beginner": "Débutant",
    "badge_reader": "Lecteur",
    "badge_scholar": "Savant",
    "badge_persistent": "Persévérant",
    "badge_expert": "Expert",
    "splashFeatures": [
      "Qui est juif ?",
      "Idées-clés avec textes originaux",
      "Traduction française intégrale (PDF)",
      "App interactive trilingue"
    ]
  }
};

window.BOOK_CARDS = [
  {
    "id": 1,
    "emoji": "📖",
    "ar": {
      "title": "من هو اليهودي ؟",
      "desc": "Démontage de la prétention sioniste à fonder une identité juive unique. Distinction massirienne entre juif religieux, ethnique et politique.",
      "young": "Démontage de la prétention sioniste à fonder une identité juive unique. Distinction massirienne entre juif religieux, ethnique et politique.",
      "verse": "من هو اليهودي ؟",
      "verseRef": "65 صفحات · ترجمة فرنسية كاملة",
      "hadith": "",
      "action": "اقرأ النص الكامل في ملف PDF"
    },
    "en": {
      "title": "Qui est juif ?",
      "desc": "Démontage de la prétention sioniste à fonder une identité juive unique. Distinction massirienne entre juif religieux, ethnique et politique.",
      "young": "Démontage de la prétention sioniste à fonder une identité juive unique. Distinction massirienne entre juif religieux, ethnique et politique.",
      "verse": "من هو اليهودي ؟",
      "verseRef": "65 pages · full French translation",
      "hadith": "",
      "action": "Read the full text in the PDF"
    },
    "fr": {
      "title": "Qui est juif ?",
      "desc": "Démontage de la prétention sioniste à fonder une identité juive unique. Distinction massirienne entre juif religieux, ethnique et politique.",
      "young": "Démontage de la prétention sioniste à fonder une identité juive unique. Distinction massirienne entre juif religieux, ethnique et politique.",
      "verse": "من هو اليهودي ؟",
      "verseRef": "65 pages · traduction française intégrale",
      "hadith": "",
      "action": "Lire le texte intégral dans le PDF"
    }
  }
];

window.BOOK_QUIZ = [];

window.BOOK_DUAS = [];

window.BOOK_ABOUT = {
  "ar": {
    "disclaimerTitle": "📚 ملاحظة",
    "disclaimer": "هذا التطبيق هو واجهة قراءة للترجمة الفرنسية لكتاب الدكتور عبد الوهاب المسيري. الترجمة كاملة ومنشورة في ملف PDF. التطبيق يعرض مختارات للاكتشاف.",
    "authorName": "د. عبد الوهاب المسيري",
    "authorDates": "١٩٣٨ — ٢٠٠٨",
    "authorBio": "مفكر وموسوعي مصري، صاحب موسوعة \"اليهود واليهودية والصهيونية\" في ٨ مجلدات. طوّر النموذج التفسيري الجديد لقراءة الحداثة الغربية والصهيونية. أكاديمي وأديب وناقد للحضارة المادية.",
    "bookTitle": "عن الكتاب",
    "bookDesc": "من هو اليهودي ؟ — Démontage de la prétention sioniste à fonder une identité juive unique. Distinction massirienne entre juif religieux, ethnique et politique.",
    "sourcesTitle": "المصادر والروابط",
    "sources": [
      "« Qui est juif ? » — ʿAbd al-Wahhāb al-Massīrī",
      "Texte arabe original — couche OCR archive.org",
      "Traduction française intégrale (gabarit massirien)",
      "📖 Unifié : <a href=\"man-huwa-al-yahudi_fr_unified.pdf\" target=\"_blank\">man-huwa-al-yahudi_fr_unified.pdf</a>",
      "🗂 Fusionné : <a href=\"man-huwa-al-yahudi_fr_merged.pdf\" target=\"_blank\">man-huwa-al-yahudi_fr_merged.pdf</a>"
    ],
    "contact": "ورشة Choughl · 2026"
  },
  "en": {
    "disclaimerTitle": "📚 Note",
    "disclaimer": "This app is a reading interface for the French translation of Dr. ʿAbd al-Wahhāb al-Massīrī's book. The full translation is published as PDF. The app showcases selected excerpts.",
    "authorName": "Dr. ʿAbd al-Wahhāb al-Massīrī",
    "authorDates": "1938 — 2008",
    "authorBio": "Egyptian thinker and encyclopedist, author of the 8-volume Encyclopedia of Jews, Judaism, and Zionism. Developed the new interpretive model for reading Western modernity and Zionism. Academic, writer, critic of materialist civilization.",
    "bookTitle": "About the Book",
    "bookDesc": "Qui est juif ? — Démontage de la prétention sioniste à fonder une identité juive unique. Distinction massirienne entre juif religieux, ethnique et politique.",
    "sourcesTitle": "Sources & links",
    "sources": [
      "« Qui est juif ? » — ʿAbd al-Wahhāb al-Massīrī",
      "Texte arabe original — couche OCR archive.org",
      "Traduction française intégrale (gabarit massirien)",
      "📖 Unifié : <a href=\"man-huwa-al-yahudi_fr_unified.pdf\" target=\"_blank\">man-huwa-al-yahudi_fr_unified.pdf</a>",
      "🗂 Fusionné : <a href=\"man-huwa-al-yahudi_fr_merged.pdf\" target=\"_blank\">man-huwa-al-yahudi_fr_merged.pdf</a>"
    ],
    "contact": "Atelier Choughl · 2026"
  },
  "fr": {
    "disclaimerTitle": "📚 Note",
    "disclaimer": "Cette app est une interface de lecture pour la traduction française du livre du Dr ʿAbd al-Wahhāb al-Massīrī. La traduction intégrale est publiée en PDF. L'app présente une sélection d'extraits.",
    "authorName": "Dr ʿAbd al-Wahhāb al-Massīrī",
    "authorDates": "1938 — 2008",
    "authorBio": "Penseur et encyclopédiste égyptien, auteur de l'Encyclopédie des Juifs, du judaïsme et du sionisme en 8 volumes. Concepteur du nouveau modèle interprétatif pour lire la modernité occidentale et le sionisme. Universitaire, écrivain, critique de la civilisation matérialiste.",
    "bookTitle": "À propos du livre",
    "bookDesc": "Qui est juif ? — Démontage de la prétention sioniste à fonder une identité juive unique. Distinction massirienne entre juif religieux, ethnique et politique.",
    "sourcesTitle": "Sources et liens",
    "sources": [
      "« Qui est juif ? » — ʿAbd al-Wahhāb al-Massīrī",
      "Texte arabe original — couche OCR archive.org",
      "Traduction française intégrale (gabarit massirien)",
      "📖 Unifié : <a href=\"man-huwa-al-yahudi_fr_unified.pdf\" target=\"_blank\">man-huwa-al-yahudi_fr_unified.pdf</a>",
      "🗂 Fusionné : <a href=\"man-huwa-al-yahudi_fr_merged.pdf\" target=\"_blank\">man-huwa-al-yahudi_fr_merged.pdf</a>"
    ],
    "contact": "Atelier Choughl · 2026"
  }
};
